version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./LoremIpsum/Dockerfile
    ports:
      - '80:80'
  li_service:
    build:
      context: .
      dockerfile: ./Services/LoremIpsum-Service/Dockerfile
    ports:
      - '80:80'